#!/bin/bash
#
# Copyright 2015 VMware, Inc.  All rights reserved.
# SPDX-License-Identifier: MIT OR GPL-3.0-only
#

BUILTIN_WRAPPER=/usr/lib/coreos/kubelet-wrapper
CUSTOM_WRAPPER={{coreos_kubelet_install_dir}}/kubelet-wrapper.sh

if [ -e "$CUSTOM_WRAPPER" ]; then
    exec "$CUSTOM_WRAPPER" "$@"
elif [ -e "$BUILTIN_WRAPPER" ]; then
    exec "$BUILTIN_WRAPPER" "$@"
fi
